### ISSUE TITLE
java.lang.ClassCastException: class com.google.cloud.hive.bigquery.repackaged.org.apache.arrow.vector.TimeStampMicroTZVector cannot be cast to class com.google.cloud.hive.bigquery.repackaged.org.apache.arrow.vector.TimeStampMicroVector

### ISSUE THREAD

**Issue by ernestobv** [GoogleCloudDataproc/hive-bigquery-connector#116]
Hello,

I encountered a ClassCastException while reading a table from BigQuery, which was created as an external table from another in BigQuery.

The error occurred with version 2.0.3.

Here is the stack trace:

`Caused by: java.lang.ClassCastException: class com.google.cloud.hive.bigquery.repackaged.org.apache.arrow.vector.TimeStampMicroTZVector cannot be cast to class com.google.cloud.hive.bigquery.repackaged.org.apache.arrow.vector.TimeStampMicroVector (com.google.cloud.hive.bigquery.repackaged.org.apache.arrow.vector.TimeStampMicroTZVector and com.google.cloud.hive.bigquery.repackaged.org.apache.arrow.vector.TimeStampMicroVector are in unnamed module of loader 'app')
        at com.google.cloud.hive.bigquery.connector.input.arrow.ArrowSerializer.serialize(ArrowSerializer.java:107)
        at com.google.cloud.hive.bigquery.connector.input.arrow.ArrowRecordReader.serializeRow(ArrowRecordReader.java:67)
        at com.google.cloud.hive.bigquery.connector.input.arrow.ArrowRecordReader.next(ArrowRecordReader.java:93)
        at com.google.cloud.hive.bigquery.connector.input.arrow.ArrowRecordReader.next(ArrowRecordReader.java:35)
        at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.doNext(HiveContextAwareRecordReader.java:360)
        ... 24 more`

I have forked the project and resolved the issue in my cloned repository. You can view the commit with my resolution here:

https://github.com/ernestobv/hive-bigquery-connector/commit/70b8a3c95d1861e621ca4bfdc0f016a803d395a9

Best regard

**Comment by ernestobv** [comment]
Hello, 

The error comes from using columns with non-coherent types between Hive and BigQuery (https://github.com/GoogleCloudDataproc/hive-bigquery-connector?tab=readme-ov-file#data-type-mapping), once the correct type mapping is used, the error no longer appears. I try to close the ticket. 

Thanks.
