### ISSUE TITLE
org.apache.hadoop.hive.ql.metadata.HiveException: Unable to find column _PARTITIONDATE 

### ISSUE THREAD

**Issue by piyu5h** [GoogleCloudDataproc/hive-bigquery-connector#96]
I am getting below exception while reading partitioned table created from create table statement provided in docs. 
Table Creation Statement

```
CREATE TABLE `bq_test`(
  `id` int COMMENT 'from deserializer',
  `count` int COMMENT 'from deserializer',
  `created_at` bigint COMMENT 'from deserializer',
  `post_id` int COMMENT 'from deserializer',
  `user_id` int COMMENT 'from deserializer',
  `updated_at` bigint COMMENT 'from deserializer',
  `is_auto_moderated` boolean COMMENT 'from deserializer'
STORED BY
  'com.google.cloud.hive.bigquery.connector.BigQueryStorageHandler'
TBLPROPERTIES (
  'bq.table'='{PROJECT}.bq_test',
  'bq.time.partition.type'='DAY')
```

Getting below exception while querying ingestion time partitioned table 
```
select id from bq_test where `_partitiondate`='2023-06-26';
```

Vertex failed, vertexName=Map 1, vertexId=vertex_1687761571976_0032_3_00, diagnostics=[Task failed, taskId=task_1687761571976_0032_3_00_000000, diagnostics=[TaskAttempt 0 failed, info=[Error: Error while running task ( failure ) : attempt_1687761571976_0032_3_00_000000_0:java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: java.io.IOException: java.lang.RuntimeException: Unable to find column _PARTITIONDATE in columns [id, count, created_at, post_id, user_id, updated_at, is_auto_moderated, _partitiontime, _partitiondate]
	at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:296)
	at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.run(TezProcessor.java:250)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:374)
	at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:73)
	at org.apache.tez.runtime.task.TaskRunner2Callable$1.run(TaskRunner2Callable.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
	at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:61)
	at org.apache.tez.runtime.task.TaskRunner2Callable.callInternal(TaskRunner2Callable.java:37)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: java.io.IOException: java.lang.RuntimeException: Unable to find column _PARTITIONDATE in columns [id, count, created_at, post_id, user_id, updated_at, is_auto_moderated, _partitiontime, _partitiondate]
	at org.apache.hadoop.hive.ql.exec.tez.MapRecordSource.pushRecord(MapRecordSource.java:80)
	at org.apache.hadoop.hive.ql.exec.tez.MapRecordProcessor.run(MapRecordProcessor.java:419)
	at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:267)
	... 16 more
Caused by: java.io.IOException: java.lang.RuntimeException: Unable to find column _PARTITIONDATE in columns [id, count, created_at, post_id, user_id, updated_at, is_auto_moderated, _partitiontime, _partitiondate]
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerChain.handleRecordReaderNextException(HiveIOExceptionHandlerChain.java:121)
	at org.apache.hadoop.hive.io.HiveIOExceptionHandlerUtil.handleRecordReaderNextException(HiveIOExceptionHandlerUtil.java:77)
	at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.doNext(HiveContextAwareRecordReader.java:365)
	at org.apache.hadoop.hive.ql.io.HiveRecordReader.doNext(HiveRecordReader.java:79)
	at org.apache.hadoop.hive.ql.io.HiveRecordReader.doNext(HiveRecordReader.java:33)
	at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.next(HiveContextAwareRecordReader.java:116)
	at org.apache.hadoop.mapred.split.TezGroupedSplitsInputFormat$TezGroupedSplitsRecordReader.next(TezGroupedSplitsInputFormat.java:151)
	at org.apache.tez.mapreduce.lib.MRReaderMapred.next(MRReaderMapred.java:116)
	at org.apache.hadoop.hive.ql.exec.tez.MapRecordSource.pushRecord(MapRecordSource.java:68)
	... 18 more
Caused by: java.lang.RuntimeException: Unable to find column _PARTITIONDATE in columns [id, count, created_at, post_id, user_id, updated_at, is_auto_moderated, _partitiontime, _partitiondate]
	at com.google.cloud.hive.bigquery.connector.input.arrow.ArrowRecordReader.serializeRow(ArrowRecordReader.java:62)
	at com.google.cloud.hive.bigquery.connector.input.arrow.ArrowRecordReader.next(ArrowRecordReader.java:93)
	at com.google.cloud.hive.bigquery.connector.input.arrow.ArrowRecordReader.next(ArrowRecordReader.java:35)
	at org.apache.hadoop.hive.ql.io.HiveContextAwareRecordReader.doNext(HiveContextAwareRecordReader.java:360)

**Comment by jphalip** [comment]
Fixed in #98, thanks!
